### ISSUE TITLE
Error with GVM with OPENVAS

### ISSUE THREAD

**Issue by rudnypc** [Secure-Compliance-Solutions-LLC/OpenVAS-Docker#1]
When I create a task and try to start some error appear.

==> /usr/local/var/log/gvm/ospd-openvas.log <==

OSPD[49] 2020-11-16 12:30:33,184: INFO: (ospd.command.command) Scan 79216e53-1840-4a4d-8524-dfa7bb861890 added to the queue in position 1.

Traceback (most recent call last):

  File "/usr/local/bin/ospd-openvas", line 11, in <module>

    load_entry_point('ospd-openvas==20.8.0', 'console_scripts', 'ospd-openvas')()

  File "/usr/local/lib/python3.8/dist-packages/ospd_openvas-20.8.0-py3.8.egg/ospd_openvas/daemon.py", line 1383, in main

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/main.py", line 160, in main

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/ospd.py", line 1255, in run

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/ospd.py", line 1398, in clean_forgotten_scans

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/ospd.py", line 1487, in get_scan_end_time

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/scan.py", line 424, in get_end_time

  File "<string>", line 2, in __getitem__

  File "/usr/lib/python3.8/multiprocessing/managers.py", line 850, in _callmethod

    raise convert_to_error(kind, result)

KeyError: 'end_time'

Error in atexit._run_exitfuncs:

Traceback (most recent call last):

  File "/usr/lib/python3.8/multiprocessing/managers.py", line 827, in _callmethod

    conn = self._tls.connection

AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/main.py", line 81, in exit_cleanup

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/ospd.py", line 438, in daemon_exit_cleanup

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/scan.py", line 242, in clean_up_pickled_scan_info

  File "/usr/local/lib/python3.8/dist-packages/ospd-20.8.1-py3.8.egg/ospd/scan.py", line 340, in get_status

  File "<string>", line 2, in get

  File "/usr/lib/python3.8/multiprocessing/managers.py", line 831, in _callmethod

    self._connect()

  File "/usr/lib/python3.8/multiprocessing/managers.py", line 818, in _connect

    conn = self._Client(self._token.address, authkey=self._authkey)

  File "/usr/lib/python3.8/multiprocessing/connection.py", line 502, in Client

    c = SocketClient(address)

  File "/usr/lib/python3.8/multiprocessing/connection.py", line 629, in SocketClient

    s.connect(address)

FileNotFoundError: [Errno 2] No such file or directory

**Comment by miyoyo** [comment]
This error seems to happen because of the `--scaninfo-store-time 12` parameter.

Keep in mind **I am running this on Podman.**

**Comment by rudnypc** [comment]
Worked, thanks @miyoyo

**Comment by Akrugerus** [comment]
Was the solution to remove the `--scan-info-store-time 12` or to change it to a different value?

**Comment by thecomet28** [comment]
> Was the solution to remove the `--scan-info-store-time 12` or to change it to a different value?

Yes, removing it is the solution.

**Comment by pixelsquared** [comment]
This issue should be resolved with the latest release.
